Repository anatechdev/mulheres-na-tecnologia, pull requests merged in 2022-10, with the labels that each got.

#4 Atualização do README - Contribuições
  README.md
Labels: documentation, hacktoberfest-accepted

#5 insere conteudo de reactjs criado por Simara Conceicao
  README.md
Labels: hacktoberfest-accepted

#7 Adicionando novas iniciativas
  README.md
Labels: hacktoberfest-accepted

#8 [Melhoria] Ordenação tópicos
  README.md
Labels: hacktoberfest-accepted

#9 Inclusões de novos conteúdos e ajustes
  README.md
Labels: hacktoberfest-accepted, Update

#10 Inclusão de novos cursos, formações e eventos
  README.md
Labels: hacktoberfest-accepted, Update

#11 Ajustes e Correções
  README.md
Labels: Update

#13 Inclusão de novo curso : Minas Programam
  README.md
Labels: hacktoberfest-accepted

#15 Add MeetUps
  README.md
Labels: hacktoberfest-accepted, Update

#16 Add Instituições e Organizações
  README.md
Labels: hacktoberfest-accepted, Update

#17 Add Comunidades
  README.md
Labels: hacktoberfest-accepted, Update

#18 Adicionando novo canal no youtube e Artigos Dev Community
  README.md
Labels: hacktoberfest-accepted

#19 add 3 canais no youtube
  README.md
Labels: hacktoberfest-accepted

#20 Adicionado Rafaella Ballerini e Mulheres de Produto
  README.md
Labels: hacktoberfest-accepted

#21 Add novos canais youtube e ajustando ordem alfabética
  README.md
Labels: hacktoberfest-accepted

#23 Adicionei ebook e link da comunidade SysAdminas
  README.md
Labels: hacktoberfest-accepted

#27 Adicionando o Coletivo Unicas
  README.md
Labels: hacktoberfest-accepted

#14 Adicionando blog
  README.md
Labels: hacktoberfest-accepted

#28 Adicionar repo sobre tecnologia e sociedade da carla
  README.md
Labels: hacktoberfest-accepted

#29 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#30 Atualização do README e Código de Conduta
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#33 Nova comunidade adicionada
  README.md
Labels: hacktoberfest-accepted

#34 Add Blog e ajustes
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#35 Adicionando comunidades e canal no youtube
  README.md
Labels: hacktoberfest-accepted

#36 Comunidade e Podcast novos adicionados
  README.md
Labels: hacktoberfest-accepted

#37 Adicionando o link correto do PyLadies Brasil
  README.md
Labels: hacktoberfest-accepted

#38 add new institution
  README.md
Labels: hacktoberfest-accepted

#39 add new youtube chanel
  README.md
Labels: hacktoberfest-accepted

#40 contribuições e alteração de link
  README.md
Labels: hacktoberfest-accepted

#43 Adicionei duas comunidades
  README.md
Labels: hacktoberfest-accepted

#47 Alteração em ordem alfabética, tópicos e mais conteúdos.
  README.md
Labels: good first issue, hacktoberfest-accepted

#51 Adicionando 3 referencias da área de tecnologia
  README.md
Labels: hacktoberfest-accepted

#52 add "GitHub Student por levxyca"
  README.md
Labels: hacktoberfest-accepted
